name: build-package

on:
  pull_request:
    paths-ignore:
      - 'examples/**'
    branches:
      - main
env:
  FIREBASE_PROJECT: firebase-dev-test
  FIRESTORE_EMULATOR_HOST: localhost:8080
          
jobs:
  build:
    name: build-package
    uses: cat-home-experts/toolshed-dotnet-shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: build
      net3: true
      testdirectory: 'source/Cathex.Firestore.UnitTests'
      emulator: 'docker-compose up integrationaction'
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.CI_GH_PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.CI_GH_PACKAGE_USERNAME }}
