name: publish-package

on:
  push:
    branches:
      - main
      - feature/init

jobs:
  build:
    name: release-package
    uses: newazmir/shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: main
      nuget: yes
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.CI_GH_PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.CI_GH_PACKAGE_USERNAME }}
