name: publish-alpha-package

on:
  push:
    paths-ignore:
      - 'examples/**'
    branches:
      - 'alpha/**'
env:
  FIREBASE_PROJECT: firebase-dev-test
  FIRESTORE_EMULATOR_HOST: localhost:8080

jobs:
  build:
    name: Publish Alpha Package
    uses: software-mgt/dotnet-shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: alpha
      testdirectory: 'source/Cathex.Firestore.UnitTests'
      net3: true
      emulator: 'docker-compose up integrationaction'
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.CI_GH_PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.CI_GH_PACKAGE_USERNAME }}
